language: java

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: releng/nu.bibi.twigcs.repository/target/repository
  on:
    branch: master
